### ISSUE TITLE
SyntaxError: Invalid character: '`' 

### ISSUE THREAD

**Issue by olegdovger** [albertjan/ember-cli-yadda#3] opened 2015-09-21 06:58 UTC
I got error SyntaxError: Invalid character: '`'  (line 1670) 
while testing in PhantomJS 2.0

It is because of single quote here:
![2015-09-21 9 55 51](https://cloud.githubusercontent.com/assets/964292/9986602/4e47007c-6047-11e5-8b54-26cfe42d4367.png)

**Comment by olegdovger** [comment] 2015-09-21 07:15
https://github.com/curit/ember-cli-yadda/pull/4

**Comment by olegdovger** [comment] 2015-09-21 07:16
[Changes here] (https://github.com/curit/ember-cli-yadda/pull/4)

**Comment by remkoboschker** [comment] 2015-09-21 07:28
This backtick start a es2015 template string https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings

**Comment by albertjan** [comment] 2015-09-21 07:41
The problem is probably that babel doesn't translate it to es5. What version of ember-cli are you on?

**Comment by olegdovger** [comment] 2015-09-21 10:55
![2015-09-21 13 52 22](https://cloud.githubusercontent.com/assets/964292/9990188/0f8e4fb8-6068-11e5-8954-3cd6d8cb2379.png)

If I run 
`phantomjs`
and then
`test string.indexOf(0)`

I got the same error - **Invalid character: '`'**

**Comment by albertjan** [comment] 2015-09-21 10:58
Yes that happens when the tests aren't being translated from es6 to es5. Could you paste your package.json file. So I can investigate a little,

**Comment by olegdovger** [comment] 2015-09-21 10:58
see previous message ) I edited it )

**Comment by olegdovger** [comment] 2015-09-21 11:00
<pre>"devDependencies": {
    "broccoli-asset-rev": "^2.1.2",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "0.5.0",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.2.0",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-inline-content": "0.4.0",
    "ember-cli-mirage": "0.1.8",
    "ember-cli-qunit": "^1.0.0",
    "ember-cli-release": "0.2.3",
    "ember-cli-simple-auth": "0.8.0",
    "ember-cli-simple-auth-devise": "0.8.0",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-styles-reloader": "0.1.8",
    "ember-cli-stylus": "1.0.5",
    "ember-cli-uglify": "^1.2.0",
    "ember-cli-yadda": "git@github.com:owm-inc/ember-cli-yadda.git",
    "ember-data": "1.13.8",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-i18n": "4.1.3"
  }</pre>

**Comment by albertjan** [comment] 2015-09-21 11:30
could you try running `ember install ember-cli-babel --save`

**Comment by albertjan** [comment] 2015-09-21 12:04
Here is an example of a working template string https://jsbin.com/joyukaxate/edit?html,js,output

**Comment by olegdovger** [comment] 2015-09-21 12:28
Error is still produced when I run `ember t`

<pre>not ok 1 PhantomJS 2.0 - global failure
    ---
        actual: >
            null
        message: >
            SyntaxError: Invalid character: '`'
        Log: |
    ...
not ok 2 PhantomJS 2.0 - global failure
    ---
        actual: >
            null
        message: >
            SyntaxError: Invalid character: '`'
        Log: |
    ...

1..2
# tests 2
# pass  0
# fail  2</pre>

I think that problem in PhantomJS or yadda library

**Comment by olegdovger** [comment] 2015-09-21 12:30
And my solution from pull request is not ideal. Is it possible to change symbol "`" to another one?

**Comment by olegdovger** [comment] 2015-09-21 13:05
[More stable solution](https://github.com/curit/ember-cli-yadda/pull/5)
What do you think about it?

**Comment by albertjan** [comment] 2015-09-21 13:11
I've reproduced it I'm looking into it If I can't find it your solution is fine :smile:

**Comment by albertjan** [comment] 2015-09-21 13:15
I found it has to do with the ordering of the packages :smile: if you put ember-cli-yadda ahead of ember-cli-babel you'll get a different error but the javascript will be translated.

**Comment by olegdovger** [comment] 2015-09-21 13:47
Yes. It works )). Right now it is enough for me but it would be nice if it work regardless of package ordering.

**Comment by albertjan** [comment] 2015-09-21 13:48
Cool :) I'm working on a more permanent fix :+1:

**Comment by manjudr** [comment] 2018-03-16 07:16
Facing the same issue

```  SyntaxError: Invalid character: '`' ``` Es6 code not supporting 
I tried with "phantomjs": "2.1" and  "phantomjs": "2.1.7" version 

@albertjan  @olegdovger 

Could you please help me on this?  What version of phantom js will support the es6 code.

**Comment by albertjan** [comment] 2018-03-16 11:19
@simonihmig @sfbwalder any idea what happened here? @manjudr did the suggested fix above not work for you?

**Comment by simonihmig** [comment] 2018-03-16 11:29
Idk. Is this related to the latest release? I see the reported issue is very old...
So please report what version of `ember-cli-yadda` you guys are using!

I agree, if string templates are still sent to the browser, something with transpilation (`ember-cli-babel`) seems broken...

**Comment by albertjan** [comment] 2018-03-16 15:47
Don't think it's release related.

**Comment by manjudr** [comment] 2018-03-17 02:37
Which version of phantom js  will support the es6 ? May I know @albertjan

**Comment by simonihmig** [comment] 2018-03-17 15:01
> Which version of phantom js  will support the es6

Phantom is actually deprecated, and if it does not support it now, it will probably never do so. The best practice of testing in a browser nowadays is using a headless version of a "real" browser, like headless Chrome.

But that is not really the point here. As said previously Babel should have transpiled that ES6 code to ES5. At least as long as you did not remove support for e.g. IE from your ember CLI app's `config/targets.js`, which I assume you haven't?

As quite a few things have changed in ember-cli-yadda across the last releases, we really do need to know the answer to this question to be able to help in any way:

> So please report what version of ember-cli-yadda you guys are using!

**Comment by manjudr** [comment] 2018-03-19 06:19
> So please report what version of ember-cli-yadda you guys are using!

@simonihmig  Currently I am not using ``` ember-cli-yadda``` We are writing a unit test cases using `jasmine framework` and `PhantomJS` browser

**Comment by simonihmig** [comment] 2018-03-19 09:43
> Currently, I am not using ember-cli-yadda

Uh, ok... but how is this then related to this issue here? If your question is in general about PhantomJS, then this is not the right place to ask for it. Please visit some PhantomJS related "forum", like their github repo or so! I honestly have no idea about specific PhantomJS details...

Closing this for now, as all reports so far are either outdated or unrelated. If someone still sees this problem in a recent release (0.3.0 for legacy APIs, or the current 0.4.0), then feel free to reopen!

**Closed by simonihmig** 2018-03-19 09:43 UTC
